const curriculum={lower:{label:'Lower Primary (Grade 1–3)',grades:['Grade 1','Grade 2','Grade 3'],subjects:['English Literacy','Kiswahili Literacy','Mathematics','Environmental Activities','Creative Arts','Religious Education','Physical Education']},upper:{label:'Upper Primary (Grade 4–6)',grades:['Grade 4','Grade 5','Grade 6'],subjects:['English','Kiswahili','Mathematics','Science and Technology','Social Studies','Agriculture','Creative Arts and Sports','Religious Education']},junior:{label:'Junior School (Grade 7–9)',grades:['Grade 7','Grade 8','Grade 9'],subjects:['English','Kiswahili','Mathematics','Integrated Science','Social Studies','Pre-Technical Studies','Agriculture','Business Studies','Creative Arts and Sports','Religious Education']},senior:{label:'Senior School (Grade 10–12)',grades:['Grade 10','Grade 11','Grade 12'],subjects:['English','Kiswahili','Mathematics','Biology','Chemistry','Physics','Geography','History and Citizenship','Business Studies','Agriculture','Computer Science','Economics','Literature','Religious Education']}};
const $=s=>document.querySelector(s), state={drafts:JSON.parse(localStorage.getItem('ktt:drafts')||'[]')};
function fillBand(key){const d=curriculum[key];$('#band').value=key;$('#grade').innerHTML=d.grades.map(x=>`<option>${x}</option>`).join('');$('#subject').innerHTML=d.subjects.map(x=>`<option>${x}</option>`).join('');document.querySelectorAll('.band').forEach(x=>x.classList.toggle('active',x.dataset.band===key))}
function setupBands(){Object.entries(curriculum).forEach(([key,d])=>{const b=document.createElement('button');b.type='button';b.className='band';b.dataset.band=key;b.textContent=d.label;b.onclick=()=>fillBand(key);$('#bands').append(b)});fillBand('lower');$('#band').onchange=e=>fillBand(e.target.value)}
function val(d,k,f='Not provided') { return d[k]?.trim()||f }
function lesson(d){return `LESSON PLAN\n==============================\nGrade: ${val(d,'grade')}\nSubject: ${val(d,'subject')}\nTerm: ${val(d,'term')}\nWeek: ${val(d,'week')}\nLesson title: ${val(d,'title')}\nStrand: ${val(d,'strand')}\nSub-strand: ${val(d,'substrand')}\n\nLearning outcomes\n${val(d,'outcomes')}\n\nLearning experiences\n${val(d,'methods')}\n\nResources\n${val(d,'resources')}\n\nAssessment evidence\n${val(d,'assessment')}\n\nDifferentiation / reflection\n${val(d,'reflection')}`}
function notes(d){return `LESSON NOTES\n==============================\n${val(d,'grade')} | ${val(d,'subject')} | ${val(d,'title')}\n\nOutcome:\n${val(d,'outcomes')}\n\nTeacher-guided and learner-centred activities:\n${val(d,'methods')}\n\nResources:\n${val(d,'resources')}\n\nAssessment and reflection:\n${val(d,'assessment')}\n${val(d,'reflection')}`}
function scheme(d){return `SCHEME OF WORK\n==============================\nGrade: ${val(d,'grade')}\nSubject: ${val(d,'subject')}\nTerm: ${val(d,'term')}\n\nWeek | Strand | Sub-strand | Learning outcome | Activities | Resources | Assessment\n${val(d,'week')} | ${val(d,'strand')} | ${val(d,'substrand')} | ${val(d,'outcomes')} | ${val(d,'methods')} | ${val(d,'resources')} | ${val(d,'assessment')}`}
function record(d){return `RECORD OF WORK\n==============================\nGrade: ${val(d,'grade')} | Subject: ${val(d,'subject')} | Term: ${val(d,'term')}\nWeek: ${val(d,'week')}\nContent covered: ${val(d,'title')}\nStrand: ${val(d,'strand')}\nEvidence / remarks: ${val(d,'assessment')}\nReflection: ${val(d,'reflection')}`}
function level(n){n=Number(n);return n>=80?'EE — Exceeding Expectation':n>=60?'ME — Meeting Expectation':n>=40?'AE — Approaching Expectation':'BE — Below Expectation'}
function report(d){const rows=(d.scores||'').split(',').map(x=>x.trim()).filter(Boolean).map(x=>{const [s,n]=x.split('=').map(y=>y.trim());return s&&n!==undefined?`${s}: ${n}/100 — ${level(n)}`:null}).filter(Boolean);return `REPORT CARD\n==============================\nLearner: ${val(d,'learner')}\nClass: ${val(d,'className')}\nTerm: ${val(d,'term')}\nTeacher: ${val(d,'teacher')}\n\nPerformance levels\nEE = Exceeding Expectation\nME = Meeting Expectation\nAE = Approaching Expectation\nBE = Below Expectation\n\n${rows.join('\n')||'No subject scores entered.'}`}
function esc(x){return x.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function render(d,rd={}){$('#output').innerHTML=[['Lesson plan',lesson(d)],['Lesson notes',notes(d)],['Scheme of work',scheme(d)],['Record of work',record(d)],['Report card',report(rd)]].map(([h,c])=>`<article class="output"><h3>${h}</h3><pre>${esc(c)}</pre></article>`).join('')}
$('#curriculum').onsubmit=e=>{e.preventDefault();render(Object.fromEntries(new FormData(e.target)),Object.fromEntries(new FormData($('#reportForm'))))};$('#reportForm').onsubmit=e=>{e.preventDefault();render(Object.fromEntries(new FormData($('#curriculum'))),Object.fromEntries(new FormData(e.target)))};$('#save').onclick=()=>{state.drafts.push(Object.fromEntries(new FormData($('#curriculum'))));localStorage.setItem('ktt:drafts',JSON.stringify(state.drafts));alert('Draft saved on this device.')};$('#print').onclick=()=>window.print();$('#printReport').onclick=()=>window.print();$('#menu').onclick=()=>$('#nav').classList.toggle('open');$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({curriculum:Object.fromEntries(new FormData($('#curriculum'))),report:Object.fromEntries(new FormData($('#reportForm'))),drafts:state.drafts},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kenya-teacher-toolkit.json';a.click()};$('#import').onclick=()=>$('#file').click();$('#file').onchange=e=>{const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result),d=x.curriculum||x.data?.curriculum||{};Object.entries(d).forEach(([k,v])=>{if($('#curriculum').elements[k])$('#curriculum').elements[k].value=v});fillBand($('#band').value);alert('Workspace imported.')}catch{alert('Invalid toolkit export file.')}};r.readAsText(e.target.files[0])};setupBands();render(Object.fromEntries(new FormData($('#curriculum'))),{});window.KenyaTeacherToolkit={curriculum,level,lesson,scheme};
