const curriculum={lower:{label:'Lower Primary (Grade 1–3)',grades:['Grade 1','Grade 2','Grade 3'],subjects:['English Literacy','Kiswahili Literacy','Mathematics','Environmental Activities','Creative Arts','Religious Education','Physical Education']},upper:{label:'Upper Primary (Grade 4–6)',grades:['Grade 4','Grade 5','Grade 6'],subjects:['English','Kiswahili','Mathematics','Science and Technology','Social Studies','Agriculture','Creative Arts and Sports','Religious Education']},junior:{label:'Junior School (Grade 7–9)',grades:['Grade 7','Grade 8','Grade 9'],subjects:['English','Kiswahili','Mathematics','Integrated Science','Social Studies','Pre-Technical Studies','Agriculture','Business Studies','Creative Arts and Sports','Religious Education']},senior:{label:'Senior School (Grade 10–12)',grades:['Grade 10','Grade 11','Grade 12'],subjects:['English','Kiswahili','Mathematics','Biology','Chemistry','Physics','Geography','History and Citizenship','Business Studies','Agriculture','Computer Science','Economics','Literature','Religious Education']}};
const timetableConfig={lower:{lessonsPerDay:6,minutes:30,weeklyLessons:31,subjects:['Mathematics','English Literacy','Kiswahili Literacy','Environmental Activities','Creative Arts','Physical Education','Religious Education','PPI']},upper:{lessonsPerDay:7,minutes:35,weeklyLessons:35,subjects:['Mathematics','English','Kiswahili','Science and Technology','Social Studies','Agriculture','Creative Arts and Sports','Religious Education','PPI']},junior:{lessonsPerDay:8,minutes:40,weeklyLessons:41,subjects:['Mathematics','English','Kiswahili','Integrated Science','Social Studies','Pre-Technical Studies','Agriculture','Business Studies','Creative Arts and Sports','Religious Education','PPI']},senior:{lessonsPerDay:8,minutes:40,weeklyLessons:40,subjects:['Mathematics','English','Kiswahili','Biology','Chemistry','Physics','Humanities / Pathway Subject','Business Studies','Computer Science','PE / Clubs','PPI']}};
const $=s=>document.querySelector(s), state={drafts:JSON.parse(localStorage.getItem('ktt:drafts')||'[]')};
function fillBand(key){const d=curriculum[key];$('#band').value=key;$('#grade').innerHTML=d.grades.map(x=>`<option>${x}</option>`).join('');$('#subject').innerHTML=d.subjects.map(x=>`<option>${x}</option>`).join('');document.querySelectorAll('.band').forEach(x=>x.classList.toggle('active',x.dataset.band===key));if(window.renderTimetableForm)window.renderTimetableForm(key)}
function setupBands(){Object.entries(curriculum).forEach(([key,d])=>{const b=document.createElement('button');b.type='button';b.className='band';b.dataset.band=key;b.textContent=d.label;b.onclick=()=>fillBand(key);$('#bands').append(b)});fillBand('lower');$('#band').onchange=e=>fillBand(e.target.value)}
function val(d,k,f='Not provided'){return d[k]?.trim()||f}
function lesson(d){return `LESSON PLAN\n==============================\nGrade: ${val(d,'grade')}\nSubject: ${val(d,'subject')}\nTerm: ${val(d,'term')}\nWeek: ${val(d,'week')}\nLesson title: ${val(d,'title')}\nStrand: ${val(d,'strand')}\nSub-strand: ${val(d,'substrand')}\n\nLearning outcomes\n${val(d,'outcomes')}\n\nLearning experiences\n${val(d,'methods')}\n\nResources\n${val(d,'resources')}\n\nAssessment evidence\n${val(d,'assessment')}\n\nDifferentiation / reflection\n${val(d,'reflection')}`}
function notes(d){return `LESSON NOTES\n==============================\n${val(d,'grade')} | ${val(d,'subject')} | ${val(d,'title')}\n\nOutcome:\n${val(d,'outcomes')}\n\nTeacher-guided and learner-centred activities:\n${val(d,'methods')}\n\nResources:\n${val(d,'resources')}\n\nAssessment and reflection:\n${val(d,'assessment')}\n${val(d,'reflection')}`}
function scheme(d){return `SCHEME OF WORK\n==============================\nGrade: ${val(d,'grade')}\nSubject: ${val(d,'subject')}\nTerm: ${val(d,'term')}\n\nWeek | Strand | Sub-strand | Learning outcome | Activities | Resources | Assessment\n${val(d,'week')} | ${val(d,'strand')} | ${val(d,'substrand')} | ${val(d,'outcomes')} | ${val(d,'methods')} | ${val(d,'resources')} | ${val(d,'assessment')}`}
function record(d){return `RECORD OF WORK\n==============================\nGrade: ${val(d,'grade')} | Subject: ${val(d,'subject')} | Term: ${val(d,'term')}\nWeek: ${val(d,'week')}\nContent covered: ${val(d,'title')}\nStrand: ${val(d,'strand')}\nEvidence / remarks: ${val(d,'assessment')}\nReflection: ${val(d,'reflection')}`}
function level(n){n=Number(n);return n>=80?'EE — Exceeding Expectation':n>=60?'ME — Meeting Expectation':n>=40?'AE — Approaching Expectation':'BE — Below Expectation'}
function report(d){const rows=(d.scores||'').split(',').map(x=>x.trim()).filter(Boolean).map(x=>{const [s,n]=x.split('=').map(y=>y.trim());return s&&n!==undefined?`${s}: ${n}/100 — ${level(n)}`:null}).filter(Boolean);return `REPORT CARD\n==============================\nLearner: ${val(d,'learner')}\nClass: ${val(d,'className')}\nTerm: ${val(d,'term')}\nTeacher: ${val(d,'teacher')}\n\nPerformance levels\nEE = Exceeding Expectation\nME = Meeting Expectation\nAE = Approaching Expectation\nBE = Below Expectation\n\n${rows.join('\n')||'No subject scores entered.'}`}
function esc(x){return x.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function render(d,rd={}){$('#output').innerHTML=[['Lesson plan',lesson(d)],['Lesson notes',notes(d)],['Scheme of work',scheme(d)],['Record of work',record(d)],['Report card',report(rd)]].map(([h,c])=>`<article class="output"><h3>${h}</h3><pre>${esc(c)}</pre></article>`).join('')}

function parseTime(value){const match=/^(\d{1,2}):(\d{2})$/.exec(value);if(!match)return 8*60+20;return Number(match[1])*60+Number(match[2])}
function clock(minutes){const hour=Math.floor(minutes/60),minute=String(minutes%60).padStart(2,'0');return `${String(hour).padStart(2,'0')}:${minute}`}
function timetableSlots(key,start,breakAfter,breakMinutes){const config=timetableConfig[key],slots=[],current=parseTime(start);for(let i=0;i<config.lessonsPerDay;i++){const offset=i>=breakAfter?breakMinutes:0;const begin=current+i*config.minutes+offset;slots.push({label:`Lesson ${i+1}`,time:`${clock(begin)}–${clock(begin+config.minutes)}`})}return slots}
function timetableRows(key,start,breakAfter,breakMinutes){const config=timetableConfig[key],slots=timetableSlots(key,start,breakAfter,breakMinutes),days=['Monday','Tuesday','Wednesday','Thursday','Friday'],subjects=config.subjects;return days.map((day,dayIndex)=>({day,cells:slots.map((slot,index)=>subjects[(dayIndex*2+index)%subjects.length])}))}
function timetableMarkup(rows,slots){return `<div class="timetable-wrap"><table class="timetable"><thead><tr><th>Day</th>${slots.map(s=>`<th>${s.label}<small>${s.time}</small></th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr><th>${row.day}</th>${row.cells.map(subject=>`<td>${subject}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function renderTimetableForm(key){const select=$('#timetableBand');if(!select)return;select.value=key;const config=timetableConfig[key];$('#lessonCount').textContent=`${config.lessonsPerDay} lessons/day · ${config.minutes} minutes · approximately ${config.weeklyLessons} lessons/week`}
function buildTimetableSection(){const section=document.createElement('section');section.id='timetable';section.className='section timetable-section';section.innerHTML=`<small class="eyebrow">Tool 05 · Timetable generator</small><h2>Generate a weekly timetable</h2><p class="muted">The defaults follow the published CBE timetable guidance currently used by this prototype. Confirm local school, pathway and county instructions before adoption.</p><form id="timetableForm" class="panel grid"><label>Grade band<select name="band" id="timetableBand"><option value="lower">Lower Primary (Grade 1–3)</option><option value="upper">Upper Primary (Grade 4–6)</option><option value="junior">Junior School (Grade 7–9)</option><option value="senior">Senior School (Grade 10–12)</option></select></label><label>First lesson starts<input name="start" type="time" value="08:20"></label><label>Break after lesson<select name="breakAfter" id="breakAfter"></select></label><label>Break length<select name="breakMinutes"><option value="20">20 minutes</option><option value="30" selected>30 minutes</option><option value="40">40 minutes</option></select></label><div class="wide timetable-meta"><strong id="lessonCount"></strong><span>Includes a PPI slot where applicable. Edit the generated table to match your school’s approved subject allocation.</span></div><div class="wide actions"><button class="btn primary" type="submit">Generate timetable</button><button class="btn" type="button" id="printTimetable">Print timetable</button></div></form><div id="timetableOutput" class="timetable-output"></div>`;document.querySelector('main').insertBefore(section,document.querySelector('#report'));const form=$('#timetableForm');form.addEventListener('submit',e=>{e.preventDefault();generateTimetable()});$('#printTimetable').onclick=()=>window.print();$('#timetableBand').onchange=e=>renderTimetableForm(e.target.value);renderTimetableForm(key);generateTimetable()}
function generateTimetable(){const data=Object.fromEntries(new FormData($('#timetableForm'))),key=data.band,config=timetableConfig[key],breakAfter=Math.max(1,Math.min(config.lessonsPerDay-1,Number(data.breakAfter)||3)),slots=timetableSlots(key,data.start,breakAfter,Number(data.breakMinutes)||30),rows=timetableRows(key,data.start,breakAfter,Number(data.breakMinutes)||30);$('#breakAfter').innerHTML=Array.from({length:config.lessonsPerDay-1},(_,i)=>`<option value="${i+1}" ${i+1===breakAfter?'selected':''}>After lesson ${i+1}</option>`).join('');$('#timetableOutput').innerHTML=`<div class="generated-heading"><h3>${curriculum[key].label} timetable</h3><span>${config.weeklyLessons} recommended lessons/week · ${config.minutes}-minute periods</span></div>${timetableMarkup(rows,slots)}<p class="timetable-note">Planning note: lesson counts and subject distribution are starting defaults, not a substitute for the latest official KICD/MoE circular or the school’s approved timetable.</p>`}

if($('#curriculum')){$('#curriculum').onsubmit=e=>{e.preventDefault();render(Object.fromEntries(new FormData(e.target)),Object.fromEntries(new FormData($('#reportForm'))))};$('#reportForm').onsubmit=e=>{e.preventDefault();render(Object.fromEntries(new FormData($('#curriculum'))),Object.fromEntries(new FormData(e.target)))};$('#save').onclick=()=>{state.drafts.push(Object.fromEntries(new FormData($('#curriculum'))));localStorage.setItem('ktt:drafts',JSON.stringify(state.drafts));alert('Draft saved on this device.')};$('#print').onclick=()=>window.print();$('#printReport').onclick=()=>window.print();$('#menu').onclick=()=>$('#nav').classList.toggle('open');$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({curriculum:Object.fromEntries(new FormData($('#curriculum'))),report:Object.fromEntries(new FormData($('#reportForm'))),drafts:state.drafts},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kenya-teacher-toolkit.json';a.click()};$('#import').onclick=()=>$('#file').click();$('#file').onchange=e=>{const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result),d=x.curriculum||x.data?.curriculum||{};Object.entries(d).forEach(([k,v])=>{if($('#curriculum').elements[k])$('#curriculum').elements[k].value=v});fillBand($('#band').value);alert('Workspace imported.')}catch{alert('Invalid toolkit export file.')}};if(e.target.files[0])r.readAsText(e.target.files[0])};setupBands();render(Object.fromEntries(new FormData($('#curriculum'))),{});buildTimetableSection()}
window.KenyaTeacherToolkit={curriculum,timetableConfig,level,lesson,scheme,timetableSlots,timetableRows};
